config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :articles
 
  root 'welcome#index'
post 'search' => 'articles#search',:as=>"search"
post 'date' => 'articles#date',:as=>"date"
post 'status' => 'articles#status',:as=>"status"
get 'vinosaran' => 'articles#index1',:as=>"index1"
get 'status' => 'articles#index2',:as=>"index2"

get 'stores/pending'

get 'stores/complete'

     resources :stores
     post 'test' => 'stores#test',:as=>"test"
get 'test' => 'stores#index5',:as=>"index5"

post 'status12' => 'stores#status12',:as=>"status12"
get 'status12' => 'stores#index7',:as=>"index7"
get '/stores/:id/print', :controller => 'stores', :action=> 'stores_print',:as=>:stores_print

end

app/models/article.rb
class Article < ActiveRecord::Base
	
	
	validates :member_no, uniqueness: true
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
	validates :name, uniqueness: true
	
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
    
@articles=Article.all


  end
 
  def show
    @articles = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 def edit
  @article = Article.find(params[:id])
end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 def search
@articles=Article.where("open_date >= ? and open_date <= ?",params[:open_date], params[:open_dates]) 
 
 end
 def index1
  @articles=Article.all
 end
  def date
@articles = Article.where(["open_date LIKE ?","%#{params[:open_date]}%"]) 
 
 end
 def index2
  @articles=Article.all
 end
  def status

@articles = Article.where("open_date >= ? and open_date <= ?",params[:open_date], params[:open_dates]).where(["status LIKE ?","%#{params[:search]}%"])
 
 end
 

  
 
  private
    def article_params
      params.require(:article).permit(:name, :father_name, :open_date, :end_date, :amount,:address, :status)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
    
@books=Book.all


  end
 
  def show
    @books = Book.find(params[:id])
  end
 
  def new
    @book = Book.new
  end
 def edit
 @book = Book.find(params[:id])
end
 
  def create
    @book = Book.new(book_params)
 
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end
 def update
    @book = Book.find(params[:id])
 
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
 
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
 
    redirect_to books_path
  end

 private
    def book_params
      params.require(:book).permit(:book_name, :amount, :phone)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
    
@stores=Store.all
  end

 
  def show
    @store = Store.find(params[:id])
  end
 
  def new
    @store = Store.new
  end
 def edit
    @store = Store.find(params[:id])
  end
 
  def create
   @store = Store.new(store_params)

 
    if @store.save
      @store.update_column("jewele_no","j0000"+@store.id.to_s)
      redirect_to @store
    else
      flash[:error]=@store.errors.messages
      render 'new'
    end
  end
   def update
    @store = Store.find(params[:id])
 
    if @store.update(store_params)
      redirect_to @store
    else
      render 'edit'
    end
  end
  def stores_print
    
    @store = Store.find(params[:id])
    
    render :template => "/stores/print"
end
 def pending
  @stores=Store.where("status=?","Pending")
 end
  def complete
  @stores=Store.where("status=?","Complete")
 end
  def destroy
    @store = Store.find(params[:id])
    @store.destroy
 
    redirect_to stores_path
  end

  def index7
  @stores=Store.all
 end
  def status12

@stores = Store.where("loan_date >= ? and loan_date <= ?",params[:loan_date], params[:loan_dates]).where(["status LIKE ?","%#{params[:search]}%"])
 
 end
 
 
  private
    def store_params
      params.require(:store).permit(:jewele_no, :member_no,:avatar, :name, :sex, :father_name, :gender, :loan_date, :gold_description, :gold_total, :gold_cross_weight, :gold_net_weight, :total_amount, :loan_amount, :status, :loan_close_date,:closing_amount,:address,:mobile,:interest_rate,:duration_amount,:total_interest,:register_person,:closed_person)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}

</style>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<script>
$(document).ready(function(){
      $("#open_date").datepicker({
          dateFormat: 'yy-mm-dd',
          onSelect: function(selected) {
            $("#open_dates").datepicker("option","minDate", selected)
          }
      });
      $("#open_dates").datepicker({
          dateFormat: 'yy-mm-dd',
          onSelect: function(selected) {
             $("#open_date").datepicker("option","maxDate", selected)
          }
      }); 
  });
</script>
</head>
<body>
<h1>Listing articles</h1>
 <%= form_tag search_path :method => 'get' do%>
<%= text_field_tag :loan_date, params[:loan_date]%>
<%= text_field_tag :loan_dates, params[:loan_dates]%>
<%= submit_tag "search"%>
<%end%>
<table>
  <tr>
    <th>S.no</th>
    <th>Name</th>
    <th>father_name</th>
    <th>open_date</th>
    <th>end_date</th>
    <th>Amount</th>
    <th>address</th>
    <th>status</th>
    
  </tr>
 
  <% @articles.each_with_index do |article,i| %>
    <tr class="act">
      <td><%= i+1 %></td>
      <%v="m0000"%>
      <td><%= article.id %></td>
      <td><%= article.name %></td>
      <td><%= article.father_name %></td>
      <td><%= article.open_date.strftime("%d-%m-%Y") %></td>
      <td><%= article.end_date.strftime("%d-%m-%Y") %></td>
      <%#= article.open_date.strftime("%d %m %Y") %>
        <td><%= article.amount %></td>
          <td><%= article.address %></td>
           <td class="test"><%= article.status %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  
</table>

<p> <%#= @articles.each.collect(&:amount).inject(:+)%> </p>

</body>
</html>

app/views/articles/index1.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<script>
$(document).ready(function(){
      $("#open_date").datepicker({
          dateFormat: 'yy-mm-dd'
          
      });
       
  });
</script>
</head>
<body>
<h1>Date By Date List</h1>
 <%= form_tag date_path :method => 'get' do%>
<%= text_field_tag :open_date, params[:open_date]%>

<%= submit_tag "date"%>
<%end%>

<table>
  <tr>
    <th>Name</th>
    <th>father_name</th>
    <th>open_date</th>
    <th>end_date</th>
    <th>Amount</th>
    <th>address</th>
    <th>status</th>
    
  </tr>
 
  <% @articles.each_with_index do |article| %>
    <tr class="act">
      <td><%= article.name %></td>
      <td><%= article.father_name %></td>
      <td><%= article.open_date.strftime("%d-%m-%Y") %></td>
      <td><%= article.end_date.strftime("%d-%m-%Y") %></td>
      <%#= article.open_date.strftime("%d %m %Y") %>
        <td><%= article.amount %></td>
          <td><%= article.address %></td>
           <td><%= article.status %></td>
      
    </tr>
  <% end %>
  
</table>

<p> <%#= @articles.each.collect(&:amount).inject(:+)%> </p>

</body>
</html>

app/views/articles/search.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>
<h1>Listing articles</h1>
 <%= form_tag search_path :method => 'get' do%>
<%= text_field_tag :open_date, params[:open_date]%>
<%= text_field_tag :open_dates, params[:open_dates]%>

<%= submit_tag "search"%>
<%end%>
<table>
  <tr>
    <th>Name</th>
    <th>father_name</th>
    <th>open_date</th>
    <th>end_date</th>
    <th>Amount</th>
    <th>address</th>
    <th>status</th>
    
  </tr>
 
  <% @articles.each_with_index do |article| %>
    <tr class="act">
      <td><%= article.name %></td>
      <td><%= article.father_name %></td>
      <td><%= article.open_date.strftime("%d-%m-%Y") %></td>
      <td><%= article.end_date.strftime("%d-%m-%Y") %></td>
      <%#= article.open_date.strftime("%d %m %Y") %>
        <td><%= article.amount %></td>
          <td><%= article.address %></td>
           <td><%= article.status %></td>
      
    </tr>
    <% end %>
    <tr >
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <%#= article.open_date.strftime("%d %m %Y") %>
        <td>Total Amount:<%= @articles.each.collect(&:amount).inject(:+)%></td>
          <td></td>
           <td></td>
      
    </tr>
  
</table>

</body>
</html>

app/views/books/new.html.erb
<%= form_for @book do |f| %>

  <p>
    <%= f.label :book_name %><br>
    <%= f.text_field :book_name %>
  </p>

 
  
  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>
 <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
  

  <p>
    <%= f.submit %>
  </p>
<% end %>




 

app/views/stores/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> </title >
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0" />
    <link href="/stylesheets/crop.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/stylesheets/resp.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/stylesheets/fonts.css" media="screen" rel="stylesheet" type="text/css" />
    <!--[if lt IE 9]>
    <link href="/stylesheets/ie.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="/javascripts/selectivizr-min.js"></script>
    <script src="/javascripts/html5shiv.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
 <link rel="stylesheet" href="/resources/demos/style.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

 <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>

<script>
$(document).ready(function(){
      $('#store_loan_date').datepicker({
    dateFormat: 'yy-mm-dd',
    changeMonth: true,
    changeYear: true,
});
$('#store_loan_close_date').datepicker({
    dateFormat: 'yy-mm-dd',
    changeMonth: true,
    changeYear: true,
});
$('#store_loan_date').datepicker().bind("change", function () {
    var minValue = $(this).val();
    minValue = $.datepicker.parseDate("yy-mm-dd", minValue);
    $('#store_loan_close_date').datepicker("option", "minDate", minValue);
    calculate();
});
$('#store_loan_close_date').datepicker().bind("change", function () {
    var maxValue = $(this).val();
    maxValue = $.datepicker.parseDate("yy-mm-dd", maxValue);
    $('#store_loan_date').datepicker("option", "maxDate", maxValue);
    calculate();
});

function calculate() {
    var d1 = $('#store_loan_date').datepicker('getDate');
    var d2 = $('#store_loan_close_date').datepicker('getDate');
    var oneDay = 24*60*60*1000;
    var diff = 0;
    if (d1 && d2) {
  
      diff = Math.round(Math.abs((d2.getTime() - d1.getTime())/(oneDay)));
    }
    s=diff/30;
   
    $('#store_duration_amount').val(s);

   m1 = $("#store_loan_amount").val();
m2 = $("#store_duration_amount").val();
v=m1*1.15/100;
k=v*m2;
n=parseInt(m1)+parseInt(k);
$("#store_total_interest").val(k);
$("#store_closing_amount").val(n);
} 
  });
</script>
<div class="print_link_block">
        <div class="buttons">
          <a href="javascript:void(o)" class="print">Print this page </a>
        </div><!--button-->
      </div><!--print_link_block-->

<style>




table {
    border-collapse: collapse;
    width: 50%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}

</style>

  </head>
  <body>
    

    <div id="wrapper">
      <div id="wrapper-header">
        
        
      </div><!--wrapper-header-->
      <div id="wrapper-container">
        <div class="row">
          <div class="container">
            
          
          
          <h1>Member Listing</h1>

<div id="test">

<table>
 <tr>
    <th>jewele_no</th>
    <th>member_no</th>
    <th>Name</th>
     <th>Sex</th>
    <th>Father Name</th>
    <th>Gender</th>
    <th>loan_date</th>
    <th>gold_description</th>
    <th>gold_total</th>
     <th>gold_cross_weight</th>
    <th>gold_net_weight</th>
    <th>total_amount</th>
    <th>loan_amount</th>
    <th>status</th>
    <th>loan_close_date</th>
    <th>closing_amount</th>
  
    <th>Address</th>
    <th>Mobile.No</th>
    
    <th colspan="3"></th>
  </tr>

  <% @stores.each do |store| %>
    <tr>
      <td><%= store.jewele_no %></td>
      <td><%= store.member_no %></td>
      <td><%= store.name %></td>
      <td><%= store.sex %></td>
      <td><%= store.father_name %></td>
      <td><%= store.gender %></td>
      <td><%= store.loan_date %></td>
      <td><%= store.gold_description %></td>
      <td><%= store.gold_total %></td>
      <td><%= store.gold_cross_weight %></td>
      <td><%= store.gold_net_weight %></td>
      <td><%= store.total_amount %></td>
      <td><%= store.loan_amount %></td>
       <td><%= store.status %></td>
      <td><%= store.loan_close_date %></td>
      <td><%= store.closing_amount %></td>
      <td><%= store.address %></td>
      <td><%= store.mobile %></td>
      
      <td><%= link_to 'Show', store_path(store) %></td>
      <td><%= link_to 'Edit', edit_store_path(store) %></td>
      <td><%= link_to 'Destroy', store_path(store),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Total Amount=<%#= @articles.each.collect(&:member_amount).inject(:+)%></td>
       <td></td>
      <td></td>
      <td></td>
      <td></td>
      
    </tr>
</table>

   </div>       
    
          
    
          </div><!--container-->
        </div><!--row-->
      </div><!--wrapper container -->
    

    </div><!--wrapper-->
    
  </body>
</html>

app/views/stores/index5.html.erb
<!DOCTYPE html>
<html>
<head>
<style>




table {
    border-collapse: collapse;
    width: 50%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}

</style>
</head>
<body>
<h1>Status List</h1>
<%logger.info "======page-name=========#{params[:page_name]}=======nameeeeee======"%>

<%logger.info "====33333===jgfhgf====vpageproperties====#{@page_properties.inspect}=======nameeeeee======"%>


<%logger.info "======page-name====#{@page_properties.inspect}=====#{params[:action].inspect}=======vvvvvvvvvv======"%>
 <%= form_tag status_path :method => 'get' do%>
<%= text_field_tag :loan_date, params[:loan_date]%>
<%= text_field_tag :loan_dates, params[:loan_dates]%>
<%= text_field_tag :search, params[:search]%>

<%= submit_tag "test",:id=>"test"%>
<%end%>

<table>
 <tr>
    <th>jewele_no</th>
    <th>member_no</th>
    <th>Name</th>
     <th>Sex</th>
    <th>Father Name</th>
    <th>Gender</th>
    <th>loan_date</th>
    <th>gold_description</th>
    <th>gold_total</th>
     <th>gold_cross_weight</th>
    <th>gold_net_weight</th>
    <th>total_amount</th>
    <th>loan_amount</th>
    <th>status</th>
    <th>loan_close_date</th>
    <th>closing_amount</th>
  
    <th>Address</th>
    <th>Mobile.No</th>
    
    <th colspan="3"></th>
  </tr>

  <% @stores.each do |store| %>
    <tr>
      <td><%= store.jewele_no %></td>
      <td><%= store.member_no %></td>
      <td><%= store.name %></td>
      <td><%= store.sex %></td>
      <td><%= store.father_name %></td>
      <td><%= store.gender %></td>
      <td><%= store.loan_date %></td>
      <td><%= store.gold_description %></td>
      <td><%= store.gold_total %></td>
      <td><%= store.gold_cross_weight %></td>
      <td><%= store.gold_net_weight %></td>
      <td><%= store.total_amount %></td>
      <td><%= store.loan_amount %></td>
       <td><%= store.status %></td>
      <td><%= store.loan_close_date %></td>
      <td><%= store.closing_amount %></td>
      <td><%= store.address %></td>
      <td><%= store.mobile %></td>
      
      <td><%= link_to 'Show', store_path(store) %></td>
      <td><%= link_to 'Edit', edit_store_path(store) %></td>
      <td><%= link_to 'Destroy', store_path(store),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Total Amount=<%#= @articles.each.collect(&:member_amount).inject(:+)%></td>
       <td></td>
      <td></td>
      <td></td>
      <td></td>
      
    </tr>
</table>


</body>
</html>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
      <script type="text/javascript">
        $(document).ready(function() {
                $("a.print").on("click",function(){
                    $("a.print").css("visibility","hidden");
                    window.print();
                });
            });
      </script>

app/views/stores/index7.html.erb
<!DOCTYPE html>
<html>
<head>
<style>




table {
    border-collapse: collapse;
    width: 50%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}

</style>
</head>
<body>
<h1>Status List</h1>
 <%= form_tag status12_path :method => 'get' do%>
<%= text_field_tag :loan_date, params[:loan_date]%>
<%= text_field_tag :loan_dates, params[:loan_dates]%>
<%= text_field_tag :search, params[:search]%>

<%= submit_tag "status12",:id=>"status"%>
<%end%>
<table>
 <tr>
    <th>jewele_no</th>
    <th>member_no</th>
    <th>Name</th>
     <th>Sex</th>
    <th>Father Name</th>
    <th>Gender</th>
    <th>loan_date</th>
    <th>gold_description</th>
    <th>gold_total</th>
     <th>gold_cross_weight</th>
    <th>gold_net_weight</th>
    <th>total_amount</th>
    <th>loan_amount</th>
    <th>status</th>
    <th>loan_close_date</th>
    <th>closing_amount</th>
  
    <th>Address</th>
    <th>Mobile.No</th>
    
    <th colspan="3"></th>
  </tr>

  <% @stores.each do |store| %>
    <tr>
      <td><%= store.jewele_no %></td>
      <td><%= store.member_no %></td>
      <td><%= store.name %></td>
      <td><%= store.sex %></td>
      <td><%= store.father_name %></td>
      <td><%= store.gender %></td>
      <td><%= store.loan_date %></td>
      <td><%= store.gold_description %></td>
      <td><%= store.gold_total %></td>
      <td><%= store.gold_cross_weight %></td>
      <td><%= store.gold_net_weight %></td>
      <td><%= store.total_amount %></td>
      <td><%= store.loan_amount %></td>
       <td><%= store.status %></td>
      <td><%= store.loan_close_date %></td>
      <td><%= store.closing_amount %></td>
      <td><%= store.address %></td>
      <td><%= store.mobile %></td>
      
      <td><%= link_to 'Show', store_path(store) %></td>
      <td><%= link_to 'Edit', edit_store_path(store) %></td>
      <td><%= link_to 'Destroy', store_path(store),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Total Amount=<%#= @articles.each.collect(&:member_amount).inject(:+)%></td>
       <td></td>
      <td></td>
      <td></td>
      <td></td>
      
    </tr>
</table>


</body>
</html>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
      <script type="text/javascript">
        $(document).ready(function() {
                $("a.print").on("click",function(){
                    $("a.print").css("visibility","hidden");
                    window.print();
                });
            });
      </script>

app/views/stores/test.html.erb
<!DOCTYPE html>
<html>
<head>
<style>




table {
    border-collapse: collapse;
    width: 50%;
}
table, td, th {
    border: 1px solid black;
}
th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}

</style>
</head>
<body>
<h1>Member Listing</h1>


<div class="print_link_block">
        <div class="buttons">
          <a href="javascript:void(o)" class="print">Print this page </a>
        </div><!--button-->
      </div><!--print_link_block-->
<table>
 <tr>
    <th>jewele_no</th>
    <th>member_no</th>
    <th>Name</th>
     <th>Sex</th>
    <th>Father Name</th>
    <th>Gender</th>
    <th>loan_date</th>
    <th>gold_description</th>
    <th>gold_total</th>
     <th>gold_cross_weight</th>
    <th>gold_net_weight</th>
    <th>total_amount</th>
    <th>loan_amount</th>
    <th>status</th>
    <th>loan_close_date</th>
    <th>closing_amount</th>
  
    <th>Address</th>
    <th>Mobile.No</th>
    
    <th colspan="3"></th>
  </tr>

  <% @stores.each do |store| %>
    <tr>
      <td><%= store.jewele_no %></td>
      <td><%= store.member_no %></td>
      <td><%= store.name %></td>
      <td><%= store.sex %></td>
      <td><%= store.father_name %></td>
      <td><%= store.gender %></td>
      <td><%= store.loan_date %></td>
      <td><%= store.gold_description %></td>
      <td><%= store.gold_total %></td>
      <td><%= store.gold_cross_weight %></td>
      <td><%= store.gold_net_weight %></td>
      <td><%= store.total_amount %></td>
      <td><%= store.loan_amount %></td>
       <td><%= store.status %></td>
      <td><%= store.loan_close_date %></td>
      <td><%= store.closing_amount %></td>
      <td><%= store.address %></td>
      <td><%= store.mobile %></td>
      
      <td><%= link_to 'Show', store_path(store) %></td>
      <td><%= link_to 'Edit', edit_store_path(store) %></td>
      <td><%= link_to 'Destroy', store_path(store),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Total Amount=<%#= @articles.each.collect(&:member_amount).inject(:+)%></td>
       <td></td>
      <td></td>
      <td></td>
      <td></td>
      
    </tr>
</table>


</body>
</html>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
      <script type="text/javascript">
        $(document).ready(function() {
                $("a.print").on("click",function(){
                    $("a.print").css("visibility","hidden");
                    window.print();
                });
            });
      </script>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>